// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	models "torrenter/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MediaProcessor is an autogenerated mock type for the MediaProcessor type
type MediaProcessor struct {
	mock.Mock
}

// ProcessDownloadedTorrent provides a mock function with given fields: ctx, media
func (_m *MediaProcessor) ProcessDownloadedTorrent(ctx context.Context, media *models.TorrentCompleteEvent) error {
	ret := _m.Called(ctx, media)

	if len(ret) == 0 {
		panic("no return value specified for ProcessDownloadedTorrent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.TorrentCompleteEvent) error); ok {
		r0 = rf(ctx, media)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMediaProcessor creates a new instance of MediaProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMediaProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MediaProcessor {
	mock := &MediaProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
