// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	media "shared/media"

	mock "github.com/stretchr/testify/mock"

	models "torrenter/internal/models"
)

// TorrentService is an autogenerated mock type for the TorrentService type
type TorrentService struct {
	mock.Mock
}

// HandleDownload provides a mock function with given fields: ctx, req, done
func (_m *TorrentService) HandleDownload(ctx context.Context, req *media.Media, done chan<- models.TorrentCompleteEvent) error {
	ret := _m.Called(ctx, req, done)

	if len(ret) == 0 {
		panic("no return value specified for HandleDownload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *media.Media, chan<- models.TorrentCompleteEvent) error); ok {
		r0 = rf(ctx, req, done)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTorrentService creates a new instance of TorrentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTorrentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TorrentService {
	mock := &TorrentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
