apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
data:
  # Base64 encode your values: echo -n "your_value" | base64
  POSTGRES_DB: <BASE64_ENCODED_DATABASE_NAME>
  POSTGRES_USER: <BASE64_ENCODED_DATABASE_USER>
  POSTGRES_PASSWORD: <BASE64_ENCODED_DATABASE_PASSWORD>
