// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	"context"

	"github.com/jbofill10/scout/backend/pkg/notifications"
	"github.com/stretchr/testify/mock"
)

// NotificationRepository is an autogenerated mock type for the NotificationRepository type
type NotificationRepository struct {
	mock.Mock
}

// CreateNotification provides a mock function with given fields: ctx, notification
func (_m *NotificationRepository) CreateNotification(ctx context.Context, notification *notifications.Notification) error {
	ret := _m.Called(ctx, notification)

	if len(ret) == 0 {
		panic("no return value specified for CreateNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *notifications.Notification) error); ok {
		r0 = rf(ctx, notification)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateNotification provides a mock function with given fields: ctx, notification
func (_m *NotificationRepository) UpdateNotification(ctx context.Context, notification *notifications.Notification) error {
	ret := _m.Called(ctx, notification)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *notifications.Notification) error); ok {
		r0 = rf(ctx, notification)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetNotification provides a mock function with given fields: ctx, tvdbID
func (_m *NotificationRepository) GetNotification(ctx context.Context, tvdbID string) (*notifications.Notification, error) {
	ret := _m.Called(ctx, tvdbID)

	if len(ret) == 0 {
		panic("no return value specified for GetNotification")
	}

	var r0 *notifications.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*notifications.Notification, error)); ok {
		return rf(ctx, tvdbID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *notifications.Notification); ok {
		r0 = rf(ctx, tvdbID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*notifications.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tvdbID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNotifications provides a mock function with given fields: ctx, limit, category, status
func (_m *NotificationRepository) GetNotifications(ctx context.Context, limit int, category string, status string) ([]notifications.Notification, error) {
	ret := _m.Called(ctx, limit, category, status)

	if len(ret) == 0 {
		panic("no return value specified for GetNotifications")
	}

	var r0 []notifications.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string, string) ([]notifications.Notification, error)); ok {
		return rf(ctx, limit, category, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, string, string) []notifications.Notification); ok {
		r0 = rf(ctx, limit, category, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]notifications.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, string, string) error); ok {
		r1 = rf(ctx, limit, category, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGrouped provides a mock function with given fields: ctx
func (_m *NotificationRepository) GetGrouped(ctx context.Context) ([]notifications.GroupedNotification, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetGrouped")
	}

	var r0 []notifications.GroupedNotification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]notifications.GroupedNotification, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []notifications.GroupedNotification); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]notifications.GroupedNotification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkAsRead provides a mock function with given fields: ctx, id
func (_m *NotificationRepository) MarkAsRead(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkAsRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Dismiss provides a mock function with given fields: ctx, id
func (_m *NotificationRepository) Dismiss(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Dismiss")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUnreadCount provides a mock function with given fields: ctx
func (_m *NotificationRepository) GetUnreadCount(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUnreadCount")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CleanupOld provides a mock function with given fields: ctx, retentionDays
func (_m *NotificationRepository) CleanupOld(ctx context.Context, retentionDays int) error {
	ret := _m.Called(ctx, retentionDays)

	if len(ret) == 0 {
		panic("no return value specified for CleanupOld")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, retentionDays)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNotificationRepository creates a new instance of NotificationRepository
func NewNotificationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationRepository {
	mock := &NotificationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
