// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	media "github.com/jbofill10/scout/backend/pkg/media"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// SchedulerRepository is an autogenerated mock type for the SchedulerRepository type
type SchedulerRepository struct {
	mock.Mock
}

// GetDueMedia provides a mock function with given fields: ctx, windowEnd
func (_m *SchedulerRepository) GetDueMedia(ctx context.Context, windowEnd time.Time) ([]media.Media, error) {
	ret := _m.Called(ctx, windowEnd)

	if len(ret) == 0 {
		panic("no return value specified for GetDueMedia")
	}

	var r0 []media.Media
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]media.Media, error)); ok {
		return rf(ctx, windowEnd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []media.Media); ok {
		r0 = rf(ctx, windowEnd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]media.Media)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, windowEnd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertDownloadHistory provides a mock function with given fields: mediaTitle, season, episode, absoluteEpisode, status, reason
func (_m *SchedulerRepository) InsertDownloadHistory(mediaTitle string, season int, episode int, absoluteEpisode int, status string, reason string) error {
	ret := _m.Called(mediaTitle, season, episode, absoluteEpisode, status, reason)

	if len(ret) == 0 {
		panic("no return value specified for InsertDownloadHistory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int, int, int, string, string) error); ok {
		r0 = rf(mediaTitle, season, episode, absoluteEpisode, status, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Schedule provides a mock function with given fields: _a0, releaseTime
func (_m *SchedulerRepository) Schedule(_a0 media.Media, releaseTime time.Time) error {
	ret := _m.Called(_a0, releaseTime)

	if len(ret) == 0 {
		panic("no return value specified for Schedule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(media.Media, time.Time) error); ok {
		r0 = rf(_a0, releaseTime)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSchedulerRepository creates a new instance of SchedulerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSchedulerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SchedulerRepository {
	mock := &SchedulerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
