// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	repository "github.com/jbofill10/scout/backend/internal/webserver/repository"

	mock "github.com/stretchr/testify/mock"
)

// SchedulerRepository is an autogenerated mock type for the SchedulerRepository type
type SchedulerRepository struct {
	mock.Mock
}

// GetDueMedia provides a mock function with given fields: ctx, windowEnd
func (_m *SchedulerRepository) GetDueMedia(ctx context.Context, windowEnd time.Time) ([]repository.DueItem, error) {
	ret := _m.Called(ctx, windowEnd)

	if len(ret) == 0 {
		panic("no return value specified for GetDueMedia")
	}

	var r0 []repository.DueItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]repository.DueItem, error)); ok {
		return rf(ctx, windowEnd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []repository.DueItem); ok {
		r0 = rf(ctx, windowEnd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.DueItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, windowEnd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkQueued provides a mock function with given fields: ctx, id
func (_m *SchedulerRepository) MarkQueued(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkQueued")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResetStaleQueued provides a mock function with given fields: ctx, olderThan
func (_m *SchedulerRepository) ResetStaleQueued(ctx context.Context, olderThan time.Duration) (int64, error) {
	ret := _m.Called(ctx, olderThan)

	if len(ret) == 0 {
		panic("no return value specified for ResetStaleQueued")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration) (int64, error)); ok {
		return rf(ctx, olderThan)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration) int64); ok {
		r0 = rf(ctx, olderThan)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Duration) error); ok {
		r1 = rf(ctx, olderThan)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSchedulerRepository creates a new instance of SchedulerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSchedulerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SchedulerRepository {
	mock := &SchedulerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
