apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webserver-db-pvc
  namespace: default
spec:
  volumeName: webserver-db-pv
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torrenter-db-pvc
  namespace: default
spec:
  volumeName: torrenter-db-pv
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi