apiVersion: v1
kind: PersistentVolume
metadata:
  name: torrenter-db-pv
  labels:
    app: torrenter
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/data/scout/torrenter
    type: DirectoryOrCreate
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: webserver-db-pv
  labels:
    app: webserver
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/data/scout/webserver
    type: DirectoryOrCreate
  volumeMode: Filesystem
