// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	models "torrenter/models"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// EpisodeExists provides a mock function with given fields: showTitle, seasonNumber, episodeNumber
func (_m *Repository) EpisodeExists(showTitle string, seasonNumber int, episodeNumber int) (bool, error) {
	ret := _m.Called(showTitle, seasonNumber, episodeNumber)

	if len(ret) == 0 {
		panic("no return value specified for EpisodeExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int, int) (bool, error)); ok {
		return rf(showTitle, seasonNumber, episodeNumber)
	}
	if rf, ok := ret.Get(0).(func(string, int, int) bool); ok {
		r0 = rf(showTitle, seasonNumber, episodeNumber)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, int, int) error); ok {
		r1 = rf(showTitle, seasonNumber, episodeNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EpisodeExistsByTvdbId provides a mock function with given fields: tvdbId, seasonNumber, episodeNumber
func (_m *Repository) EpisodeExistsByTvdbId(tvdbId string, seasonNumber int, episodeNumber int) (bool, error) {
	ret := _m.Called(tvdbId, seasonNumber, episodeNumber)

	if len(ret) == 0 {
		panic("no return value specified for EpisodeExistsByTvdbId")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int, int) (bool, error)); ok {
		return rf(tvdbId, seasonNumber, episodeNumber)
	}
	if rf, ok := ret.Get(0).(func(string, int, int) bool); ok {
		r0 = rf(tvdbId, seasonNumber, episodeNumber)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, int, int) error); ok {
		r1 = rf(tvdbId, seasonNumber, episodeNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLibraryByType provides a mock function with given fields: libType
func (_m *Repository) GetLibraryByType(libType string) (int, error) {
	ret := _m.Called(libType)

	if len(ret) == 0 {
		panic("no return value specified for GetLibraryByType")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int, error)); ok {
		return rf(libType)
	}
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(libType)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(libType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPreferredLibrary provides a mock function with given fields: libType
func (_m *Repository) GetPreferredLibrary(libType string) (models.PlexLibrary, error) {
	ret := _m.Called(libType)

	if len(ret) == 0 {
		panic("no return value specified for GetPreferredLibrary")
	}

	var r0 models.PlexLibrary
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.PlexLibrary, error)); ok {
		return rf(libType)
	}
	if rf, ok := ret.Get(0).(func(string) models.PlexLibrary); ok {
		r0 = rf(libType)
	} else {
		r0 = ret.Get(0).(models.PlexLibrary)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(libType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MediaExists provides a mock function with given fields: id
func (_m *Repository) MediaExists(id string) (bool, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for MediaExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetPreferredLibrary provides a mock function with given fields: id, libType
func (_m *Repository) SetPreferredLibrary(id int, libType string) error {
	ret := _m.Called(id, libType)

	if len(ret) == 0 {
		panic("no return value specified for SetPreferredLibrary")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, string) error); ok {
		r0 = rf(id, libType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertLibraries provides a mock function with given fields: libs
func (_m *Repository) UpsertLibraries(libs models.PlexLibrariesResponse) {
	_m.Called(libs)
}

// UpsertMovies provides a mock function with given fields: movies
func (_m *Repository) UpsertMovies(movies models.PlexMovieLibraryData) {
	_m.Called(movies)
}

// UpsertShows provides a mock function with given fields: shows
func (_m *Repository) UpsertShows(shows *models.PlexShowLibraryData) {
	_m.Called(shows)
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
