[package]
name = "webserver"
version = "0.1.0"
edition = "2021"

[dependencies]
tide = "0.16.0"
async-std = { version = "1.6.0", features = ["attributes", "tokio1"] }
serde = { version = "1.0", features = ["derive"] }
reqwest = "0.12.7"
