// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// PlexService is an autogenerated mock type for the PlexService type
type PlexService struct {
	mock.Mock
}

// SyncPlexLibrary provides a mock function with given fields: ctx
func (_m *PlexService) SyncPlexLibrary(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPlexService creates a new instance of PlexService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlexService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlexService {
	mock := &PlexService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
