// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	dlstatus "github.com/jbofill10/scout/backend/pkg/dlstatus"

	media "github.com/jbofill10/scout/backend/pkg/media"

	mock "github.com/stretchr/testify/mock"

	models "github.com/jbofill10/scout/backend/internal/torrenter/models"
)

// TorrentService is an autogenerated mock type for the TorrentService type
type TorrentService struct {
	mock.Mock
}

// HandleDownload provides a mock function with given fields: ctx, req, done
func (_m *TorrentService) HandleDownload(ctx context.Context, req *media.Media, done chan<- models.TorrentCompleteEvent) ([]dlstatus.EpisodeResult, error) {
	ret := _m.Called(ctx, req, done)

	if len(ret) == 0 {
		panic("no return value specified for HandleDownload")
	}

	var r0 []dlstatus.EpisodeResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *media.Media, chan<- models.TorrentCompleteEvent) ([]dlstatus.EpisodeResult, error)); ok {
		return rf(ctx, req, done)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *media.Media, chan<- models.TorrentCompleteEvent) []dlstatus.EpisodeResult); ok {
		r0 = rf(ctx, req, done)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dlstatus.EpisodeResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *media.Media, chan<- models.TorrentCompleteEvent) error); ok {
		r1 = rf(ctx, req, done)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveUUIDTag provides a mock function with given fields: ctx, hash, uuid
func (_m *TorrentService) RemoveUUIDTag(ctx context.Context, hash string, uuid string) error {
	ret := _m.Called(ctx, hash, uuid)

	if len(ret) == 0 {
		panic("no return value specified for RemoveUUIDTag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, hash, uuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTorrentService creates a new instance of TorrentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTorrentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TorrentService {
	mock := &TorrentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
