apiVersion: v1
kind: Service
metadata:
  name: webserver-service
  namespace: default
spec:
  selector:
    app: webserver
  ports:
  - port: 22920
    targetPort: 22920
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: tvdb-proxy-service
  namespace: default
spec:
  selector:
    app: tvdb-proxy
  ports:
  - port: 22000
    targetPort: 22000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: torrenter-service
  namespace: default
spec:
  selector:
    app: torrenter
  ports:
  - port: 22001
    targetPort: 22001
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: default
spec:
  selector:
    app: ui
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: default
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP