-- Drop all show-related tables with CASCADE
DROP TABLE IF EXISTS EpisodeMedia CASCADE;
DROP TABLE IF EXISTS Episodes CASCADE;
DROP TABLE IF EXISTS Seasons CASCADE;
DROP TABLE IF EXISTS Shows CASCADE;