// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/jbofill10/scout/backend/internal/torrenter/models"
	notifications "github.com/jbofill10/scout/backend/pkg/notifications"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// EpisodeExistsByTvdbId provides a mock function with given fields: ctx, tvdbId, season, episode
func (_m *Repository) EpisodeExistsByTvdbId(ctx context.Context, tvdbId string, season int, episode int) (bool, error) {
	ret := _m.Called(ctx, tvdbId, season, episode)

	if len(ret) == 0 {
		panic("no return value specified for EpisodeExistsByTvdbId")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) (bool, error)); ok {
		return rf(ctx, tvdbId, season, episode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) bool); ok {
		r0 = rf(ctx, tvdbId, season, episode)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, tvdbId, season, episode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLibraryByType provides a mock function with given fields: ctx, libType
func (_m *Repository) GetLibraryByType(ctx context.Context, libType string) (int, error) {
	ret := _m.Called(ctx, libType)

	if len(ret) == 0 {
		panic("no return value specified for GetLibraryByType")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, libType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, libType)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, libType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMovieBaseDirectory provides a mock function with given fields: ctx, tvdbId
func (_m *Repository) GetMovieBaseDirectory(ctx context.Context, tvdbId string) (string, error) {
	ret := _m.Called(ctx, tvdbId)

	if len(ret) == 0 {
		panic("no return value specified for GetMovieBaseDirectory")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, tvdbId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, tvdbId)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tvdbId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPreferredLibrary provides a mock function with given fields: ctx, libType
func (_m *Repository) GetPreferredLibrary(ctx context.Context, libType string) (models.PlexLibrary, error) {
	ret := _m.Called(ctx, libType)

	if len(ret) == 0 {
		panic("no return value specified for GetPreferredLibrary")
	}

	var r0 models.PlexLibrary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (models.PlexLibrary, error)); ok {
		return rf(ctx, libType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) models.PlexLibrary); ok {
		r0 = rf(ctx, libType)
	} else {
		r0 = ret.Get(0).(models.PlexLibrary)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, libType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPreferredUploaders provides a mock function with given fields: ctx, mediaType, isAnime
func (_m *Repository) GetPreferredUploaders(ctx context.Context, mediaType string, isAnime bool) ([]string, error) {
	ret := _m.Called(ctx, mediaType, isAnime)

	if len(ret) == 0 {
		panic("no return value specified for GetPreferredUploaders")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) ([]string, error)); ok {
		return rf(ctx, mediaType, isAnime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) []string); ok {
		r0 = rf(ctx, mediaType, isAnime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = rf(ctx, mediaType, isAnime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetShowBaseDirectory provides a mock function with given fields: ctx, tvdbId
func (_m *Repository) GetShowBaseDirectory(ctx context.Context, tvdbId string) (string, error) {
	ret := _m.Called(ctx, tvdbId)

	if len(ret) == 0 {
		panic("no return value specified for GetShowBaseDirectory")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, tvdbId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, tvdbId)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tvdbId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertDownloadHistory provides a mock function with given fields: ctx, mediaTitle, season, episode, absoluteEpisode, torrentHash, status, reason
func (_m *Repository) InsertDownloadHistory(ctx context.Context, mediaTitle string, season int, episode int, absoluteEpisode int, torrentHash string, status string, reason string) error {
	ret := _m.Called(ctx, mediaTitle, season, episode, absoluteEpisode, torrentHash, status, reason)

	if len(ret) == 0 {
		panic("no return value specified for InsertDownloadHistory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, int, string, string, string) error); ok {
		r0 = rf(ctx, mediaTitle, season, episode, absoluteEpisode, torrentHash, status, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MovieExistsByTvdbId provides a mock function with given fields: ctx, tvdbId
func (_m *Repository) MovieExistsByTvdbId(ctx context.Context, tvdbId string) (bool, error) {
	ret := _m.Called(ctx, tvdbId)

	if len(ret) == 0 {
		panic("no return value specified for MovieExistsByTvdbId")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, tvdbId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, tvdbId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tvdbId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MediaExists provides a mock function with given fields: ctx, id
func (_m *Repository) MediaExists(ctx context.Context, id string) (bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MediaExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetPreferredLibrary provides a mock function with given fields: ctx, id, libType
func (_m *Repository) SetPreferredLibrary(ctx context.Context, id int, libType string) error {
	ret := _m.Called(ctx, id, libType)

	if len(ret) == 0 {
		panic("no return value specified for SetPreferredLibrary")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = rf(ctx, id, libType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateDownloadHistoryStatus provides a mock function with given fields: ctx, torrentHash, status, reason
func (_m *Repository) UpdateDownloadHistoryStatus(ctx context.Context, torrentHash string, status string, reason string) error {
	ret := _m.Called(ctx, torrentHash, status, reason)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDownloadHistoryStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, torrentHash, status, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertLibraries provides a mock function with given fields: ctx, libs
func (_m *Repository) UpsertLibraries(ctx context.Context, libs models.PlexLibrariesResponse) {
	_m.Called(ctx, libs)
}

// UpsertMovies provides a mock function with given fields: ctx, movies
func (_m *Repository) UpsertMovies(ctx context.Context, movies models.PlexMovieLibraryData) {
	_m.Called(ctx, movies)
}

// UpsertShows provides a mock function with given fields: ctx, shows
func (_m *Repository) UpsertShows(ctx context.Context, shows *models.PlexShowLibraryData) {
	_m.Called(ctx, shows)
}

// CreateNotification provides a mock function with given fields: ctx, notification
func (_m *Repository) CreateNotification(ctx context.Context, notification *notifications.Notification) error {
	ret := _m.Called(ctx, notification)

	if len(ret) == 0 {
		panic("no return value specified for CreateNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *notifications.Notification) error); ok {
		r0 = rf(ctx, notification)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetNotification provides a mock function with given fields: ctx, tvdbID
func (_m *Repository) GetNotification(ctx context.Context, tvdbID string) (*notifications.Notification, error) {
	ret := _m.Called(ctx, tvdbID)

	if len(ret) == 0 {
		panic("no return value specified for GetNotification")
	}

	var r0 *notifications.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*notifications.Notification, error)); ok {
		return rf(ctx, tvdbID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *notifications.Notification); ok {
		r0 = rf(ctx, tvdbID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*notifications.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tvdbID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateNotification provides a mock function with given fields: ctx, notification
func (_m *Repository) UpdateNotification(ctx context.Context, notification *notifications.Notification) error {
	ret := _m.Called(ctx, notification)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *notifications.Notification) error); ok {
		r0 = rf(ctx, notification)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
